<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-PUJJMK1" failures="1" tests="7" name="Test" time="48.504" errors="0" timestamp="2024-03-12T11:38:58 IST">
  <testcase classname="com.scenario.automate.HandleAlertTests" name="cancelAlertTest" time="10.45"/>
  <testcase classname="com.scenario.automate.HandleAlertTests" name="handleAlertTest" time="4.33"/>
  <testcase classname="com.scenario.automate.HandleAlertTests" name="restApiTestTwo" time="2.309"/>
  <testcase classname="com.scenario.automate.HandleAlertTests" name="sendAlertMessageTest" time="12.064"/>
  <testcase classname="com.scenario.automate.HandleAlertTests" name="testClosePopUp" time="5.928">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.scenario.automate.HandleAlertTests.testClosePopUp(HandleAlertTests.java:124)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testClosePopUp -->
  <testcase classname="com.scenario.automate.RestApiTest" name="restApiTestOne" time="0.174"/>
  <testcase classname="com.scenario.automate.RestApiTest" name="restApiTestTwo" time="0.16"/>
</testsuite> <!-- Test -->
